-- Adicionar campo is_starter para identificar cartas do starter deck
ALTER TABLE public.cards 
ADD COLUMN IF NOT EXISTS is_starter BOOLEAN DEFAULT FALSE;

-- Criar índice para melhorar performance de consultas por starter cards
CREATE INDEX IF NOT EXISTS idx_cards_is_starter ON public.cards(is_starter);

-- Inserir cartas starter padrão se não existirem
INSERT INTO public.cards (
  id,
  name,
  type,
  rarity,
  cost_coins,
  cost_food,
  cost_materials,
  cost_population,
  effect,
  phase,
  use_per_turn,
  is_reactive,
  is_active,
  is_starter,
  slug,
  tags,
  created_at,
  updated_at
) VALUES 
  (
    gen_random_uuid(),
    'Pequeno Jardim',
    'farm',
    'common',
    0,
    0,
    0,
    0,
    'Produz 1 comida por turno.',
    'action',
    0,
    false,
    true,
    true,
    'pequeno-jardim',
    ARRAY['starter', 'farm', 'production'],
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Barraca',
    'city',
    'common',
    0,
    0,
    0,
    0,
    'Fornece 1 população imediatamente.',
    'action',
    0,
    false,
    true,
    true,
    'barraca',
    ARRAY['starter', 'city', 'population'],
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Colheita Básica',
    'action',
    'common',
    0,
    0,
    0,
    0,
    'Ganhe 1 comida instantaneamente.',
    'action',
    1,
    false,
    true,
    true,
    'colheita-basica',
    ARRAY['starter', 'action', 'food'],
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Fazenda Simples',
    'farm',
    'common',
    0,
    0,
    0,
    0,
    'Produz 1 comida quando ativada por dado.',
    'action',
    0,
    false,
    true,
    true,
    'fazenda-simples',
    ARRAY['starter', 'farm', 'dice'],
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Oficina Simples',
    'city',
    'common',
    0,
    0,
    0,
    0,
    'Produz 1 material por turno.',
    'action',
    0,
    false,
    true,
    true,
    'oficina-simples',
    ARRAY['starter', 'city', 'production'],
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Comércio Simples',
    'action',
    'common',
    0,
    0,
    0,
    0,
    'Ganhe 1 moeda instantaneamente.',
    'action',
    1,
    false,
    true,
    true,
    'comercio-simples',
    ARRAY['starter', 'action', 'coins'],
    NOW(),
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;

-- Comentário sobre o campo
COMMENT ON COLUMN public.cards.is_starter IS 'Indica se a carta faz parte do deck inicial (starter deck)'; 