// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaphpsvzwzlpzsjsgsja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhcGhwc3Z6d3pscHpzanNnc2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDY0OTUsImV4cCI6MjA2ODk4MjQ5NX0.962eA_Kh8obqaKS5-UxJnc2f2EVAtBlUM9W88-yCdOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});